[package]
name = "base64-kenji"
description = "Base64 encryption and decryption"
repository = "https://github.com/raphael-gi/Base64"
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
